services:
  web:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    container_name: qa-app  

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    container_name: qa-cypress
    depends_on:
      - web 
    environment:
      - CYPRESS_baseUrl=http://web:3000
    volumes:
      - ./cypress:/e2e/cypress